version: "3.8"

services:
    plant-chat:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - ./data:/app/data
        environment:
            - GEMINI_API_KEY=${GEMINI_API_KEY}
            - GEMINI_MODEL=${GEMINI_MODEL}
        restart: unless-stopped
